### ISSUE TITLE
No such file or directory: './data/training/train_imcrop_list.txt'

### ISSUE THREAD

**Issue by ruotianluo** [andrewliao11/Natural-Language-Object-Retrieval-tensorflow#1]
When I tried to run the 5th step of preprocessing, I met the problem of:
No such file or directory: './data/training/train_imcrop_list.txt'

(I also met problem in 4th step which told me no vocabulary.txt, then I copy from the author's repository)

**Comment by andrewliao11** [comment]
Thanks for your reminder. I'll upload it to this repo!
Basically, ***train_imcrop_list.txt*** is just a file containing all the cropped image names.
